[[tcp_reverse_proxys]]
    listen = 7001         # 反向代理监听端口
    app_id = "hyperchain" # 预留

[remote]
    reconnect_time = "1s" # 本 proxy 与对面 proxy 重连的时间间隔
    address = ["127.0.0.1"] # 对面多个 proxy 的 IP 地址
    http_port = [12002]           # 对面多个 proxy 监听的 http 端口
    tcp_port = [4323]               # 对面多个 proxy 对应的 pier 的 p2p 端口

[http]
    listen = 12001
    http2_enable = true
    [http.request]
        max_content_length = 10485760 # 10*1024*1024
        timeout = "60s"
        allow_origins = ["*"]

[security]
    [security.tls]
        enable = true
        tlsCAPath = "config/tlscerts/tlsca.ca"
        tlsCertPath = "config/tlscerts/tls_peer1.cert"
        tlsPrivPath = "config/tlscerts/tls_peer1.priv"
        tlsDomain = "hyperchain.cn"