[[tcp_reverse_proxys]]
    listen = 7022         # 反向代理监听端口
    app_id = "hyperchain" # 预留

[remote]
    reconnect_time = "1s" # 本 proxy 与对面 proxy 重连的时间间隔
    address = ["127.0.0.1", "127.0.0.1"]       # 对面多个 proxy 的 IP 地址
    http_port = [12001, 12011]           # 对面多个 proxy 监听的 http 端口

[http]
    listen = 12022
    http2_enable = true
    cancel_timeout = "5s"  # 仅用于pier信号切换goroutine，表示一个http请求从连接建立到读取response body的超时时间，到达超时时间会关闭请求
    retry_duration = "10s" # 仅用于pier信号切换goroutine，表示多久去遍历一次所有的对端http端口，向他们发送心跳检测
    all_failed_limit = 30  # 仅用于pier信号切换goroutine，表示每次遍历所有的对端http端口请求都发送失败了的次数上限，达到上限后会触发一次pier切换
    [http.request]
        max_content_length = 10485760 # 10*1024*1024
        timeout = "60s"
        allow_origins = ["*"]

[security]
    [security.tls]
        enable = true
        tlsCAPath = "config/tlscerts/tls.ca"
        tlsCertPath = "config/tlscerts/tls.cert"
        tlsPrivPath = "config/tlscerts/tls.priv"
        tlsDomain = "mloong"
