title = "Pier"

[port]
http = 44544
pprof = 44555

[log]
level = "info"
dir = "logs"
filename = "pier.log"
report_caller = true
[log.module]
api_server = "info"
appchain_mgr = "info"
bxh_lite = "info"
executor = "info"
exchanger = "info"
monitor = "info"
peer_mgr = "info"
router = "info"
rule_mgr = "info"
swarm = "info"
syncer = "info"
direct_adapter = "info"
union_adapter = "info"
appchain_adapter = "info"
proxy = "info"

[mode]
type = "direct" # relay, direct or union
[mode.relay]
addrs = ["localhost:60011", "localhost:60012"]
timeout_limit = "1s"
quorum = 2
bitxhub_id = "1356"
enable_offchain_transmission = false
[mode.direct]
gas_limit = 0x5f5e100

[mode.union]
addrs = ["localhost:60011", "localhost:60012", "localhost:60013", "localhost:60014"]
providers = 1

[security]
enable_tls = false
access_cert = ["node1.cert", "node2.cert", "node3.cert", "node4.cert"]
access_key = "node.priv"
tlsca = "certs/agency.cert"
common_name = "BitXHub"

[HA]
mode = "redis"

[appchain]
id = "chain2"
plugin = "appchain_plugin"
config = "fabric"

[tss]
enable_tss = false

[redis]
#address = "10.10.97.125:6379"
#password = ""
address = "172.22.67.36:6379"
auth_enable = false
auth_secret = "OINbAi2YQT93NHGx/4y4eg=="
database = 15
master_lock_prefix = "lock_master"
send_lock_prefix = "lock_send"
master_lease_renewal = 5
master_lease_timeout = 10
send_lease_timeout = 3
self_port = 0

[proxy]
enable = true # for more proxy related configuration, see proxy.toml
