[[tcp_reverse_proxys]]
    listen = 7002         # 反向代理监听端口
    app_id = "hyperchain" # 预留
    server = "127.0.0.1:4321" # 被代理服务的 IP 和 Port，通常为最终目标节点的地址

[http]
    listen = 12002
    http2_enable = true
    [http.request]
        max_content_length = 10485760 # 10*1024*1024
        timeout = "60s"
        allow_origins = ["*"]
    [http.remote]
        address = ["127.0.0.1:12001"]
        reconnect_time = "1s"

[security]
    [security.tls]
        enable = true
        tlsCAPath = "config/tlscerts/tlsca.ca"
        tlsCertPath = "config/tlscerts/tls_peer1.cert"
        tlsPrivPath = "config/tlscerts/tls_peer1.priv"
        tlsDomain = "hyperchain.cn"
